# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

minimal_mistakes_skin    : "default" # "air", "contrast", "dark", "dirt", "mint", "sunrise"

# Site Settings
locale                   : "en"
title                    : "Khaled Alhabache"
title_separator          : "-"
name                     : "Khaled Alhabache"
description              : "Tech Blog"
url                      : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "khelll/blog.khd.me" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "disqus" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :  "blog-khd-me"
atom_feed:
  path                   : # blank (default) uses feed.xml

# SEO Related
google_site_verification :

# Social Sharing
twitter:
  username               : "khelll"
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :


# Site Author
author:
  name             : "Khaled Alhabache"
  avatar           : "/assets/khelll.jpg"
  bio              : "Software Engineer"
  location         : 
  email            :
  uri              : https://khd.me
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "khelll"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : # "john-doe-12345678" (the last part of your profile url, e.g. https://www.linkedin.com/in/john-doe-12345678)
  pinterest        :
  soundcloud       :
  stackoverflow    : "124504/khelll" # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  tumblr           :
  twitter          : "khelll"
  vine             :
  weibo            :
  xing             :
  youtube          : # "https://youtube.com/c/MichaelRoseDesign"

url: "https://blog.khd.me"
theme: minimal-mistakes-jekyll
excerpt_separator: ""
permalink: /:year/:month/:day/:title
paginate: 10
category_archive:
  type: jekyll-archives
  path: /category/
tag_archive:
  type: jekyll-archives
  path: /tag/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /category/:name/
    tag: /tag/:name/

plugins:
  - jekyll-archives
